env:
  es6: true
  amd: true
parser: babel-eslint
plugins:
  - flowtype
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
globals:
  module:
    - true
    - true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
